# =============================================================================
# HYDRA-UMC-DATALAKE - src/hydra_umc_datalake/__init__.py
# Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
# GPL-3.0 - see LICENSE
# =============================================================================
"""HYDRA-UMC-DATALAKE - scalable time-series storage for industrial robotic data.

Long-term memory of the factory: high-resolution storage (InfluxDB/
TimescaleDB) for all telemetry generated by the ecosystem. Parent
integrator of HYDRA-UMC-TELEMETRY-COLLECTOR (ingestion),
HYDRA-UMC-ANOMALY-DETECTOR (predictive maintenance) and
HYDRA-UMC-PRODUCTION-REPORTS (KPI/OEE reporting) - see docker-compose.yml
for how the three are wired together.
"""

__version__ = "0.0.8"